### ISSUE TITLE
Add another section

### ISSUE THREAD

**Issue by rozzilla** [trekhleb/javascript-algorithms#31]
You've created a wonderful repository!
It's really interesting, especially for learning purposes, like in my case.

What do you think about adding a new section that explains how to calculate 3D geometry functions?

**Comment by trekhleb** [comment]
Thank you for your feedback @rozzilla !
I think it might be a good idea to have 3D related algorithms as well.
If you don't mind just create another pull request with one of the 3D geometry related algorithms (with tests and README explanations) and I'll add this new section to main README afterwards.

**Comment by Bladefidz** [comment]
I will be working on Kd-tree and pull it in about next week. Can you prepare the section, @trekhleb?

**Comment by trekhleb** [comment]
@Bladefidz 
I believe k-d tree is a data structure and thus it may be put in Data Structures partition. No need to create new section for that. New section will be created for separate algorithm(s) related to 3D once PR with such algorithm will been provided by someone.

@rozzilla  @Bladefidz 
Meanwhile I'll close this issue since there is no action items related to it until community will provide 3D related PRs.
