### ISSUE TITLE
Proposal - we can rewrite everything in the Typescript?

### ISSUE THREAD

**Issue by mikerudenko** [trekhleb/javascript-algorithms#327]

**Comment by baer95** [comment]
What would be the benefit of that? What is your reasoning for this proposal?

**Comment by adamchenwei** [comment]
maybe he meant to have a typescript "version" of this. I guess just for fun lol

**Comment by lazarljubenovic** [comment]
Such a version would be hardly "just for fun lol".

The benefit would be more understandable code for sure. Opening code and trying to figure out what kind of data structure did someone imagine really puts me off from looking into what's been developed already. With static type information available, it would be much easier to follow code.

**Comment by mikerudenko** [comment]
And also "comments as param typings" left more space in code

**Comment by mikerudenko** [comment]
@adamchenwei @baer95 @lazarljubenovic i think this is better

```  toArray(): LinkedListNode[] {
```
instead of this

```/**
   * @return {LinkedListNode[]}
   */
  toArray() {
```

**Comment by mikerudenko** [comment]
@trekhleb what do you this about this?

**Comment by lazarljubenovic** [comment]
I don't think this repo will accept TypeScript. The name is `javascript-algorithms`. You can start a community collaboration project if you think you can handle it.

**Comment by trekhleb** [comment]
@mikerudenko thank you for suggestion. The idea of using Typescript is great. The most interesting part of TypeScript for me in scope of your suggestion would be to replace JSDocs with static types and interfaces. But the reason why I didn't use TypeScript from very beginning and why I tend to use pure ES6 for now is because I wanted to **make this project as simple as possible**. And TypeScript would introduce additional layer of complexity in form of code transpilation (for both the implementation and the tests) and it would require to learning the TS syntax for repository consumers. These two issues are for sure not that hard to resolve. But still this is another layer of complexity that I would tend to avoid for now.

**Comment by SHISME** [comment]
I just ues ts to realize a avl tree for practice，this is my repository，if you have interest

[https://github.com/SHISME/typescript-avl](https://github.com/SHISME/typescript-avl)
