### ISSUE TITLE
What should be returned by the remove method of the BinarySearchTreeNode?

### ISSUE THREAD

**Issue by m-maksyutin** [trekhleb/javascript-algorithms#57]
Hi! The `remove` method returns a BinarySearchTreeNode object. But there is one uncertain moment. What should be contained in the properties of this object, such as the `parent`, `left`, `right`? Are these properties relevant? Or they must be null?

**Comment by rakshithjk** [comment]
I think that properties of the returned object correspond to the tree state before the node is deleted.

``` 110.         nodeToRemove.value = nodeToRemove.right.value;```

You have changed the value of nodeToRemove with the value that has to be replaced (in the example you have mentioned, 30).Now when you return nodeToRemove.value it would return 30 whereas 20 was expected.Store the value of nodeToRemove is another variable and return that

**Comment by trekhleb** [comment]
Yes, you right @m-maksyutin, there is an uncertainty in removal method. To avoid similar confusion I've changed the code so that removal method will return boolean (whether node has been successfully deleted or not). Because returning the node truly brings confusion about its value, left, right and parent properties.
