### ISSUE TITLE
playground minimal code

### ISSUE THREAD

**Issue by joanillo** [trekhleb/javascript-algorithms#705]
Just for clarifying, I want to test in playground this minimal code:

const linkedList = new LinkedList();
linkedList.append('aaa');
linkedList.append('bbb');
console.log(linkedList.reverse().toString());

I got it, but I needed some changes:
-adding "type": "module"," in my package.json
-adding extension .js in my imports
-finally executing: $ node src/playground/playground.js 

but must be easier, I think I'm missing something (sure because my lack of knowledge about ES6 modules).
May be it is a good idea to clarify this point at README. TIA

**Comment by trekhleb** [comment]
Hi @joanillo 

I've added some more details to the playground files. The idea is to continue using the test-driven approach for the playground as we use it for the rest of the algorithms. It basically means that instead of running the `node src/playground/playground.js` directly the user would run `npm test -- 'playground'` instead.

The code, in this case, may look something like this:

In `playground.js`:

```javascript
// Import any algorithmic dependencies you need for your playground code here.
import factorial from '../algorithms/math/factorial/factorial';

// Write your playground code inside the playground() function.
// Test your code from __tests__/playground.test.js
// Launch playground tests by running: npm test -- 'playground'
function playground() {
  // Replace the next line with your playground code.
  return factorial(5);
}

export default playground;
```

In `__test__/playground.test.js`:

```javascript
import playground from '../playground';

describe('playground', () => {
  it('should return correct results', () => {
    // Replace the next dummy test with your playground function tests.
    expect(playground()).toBe(120);
  });
});
```

I hope this helps.
